---
title: "Inspecting DFMs"
output: html_document
date: "2024-02-11"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(quanteda)
library(quanteda.textstats)
library(igraph)
library(ggplot2)
library(ggrepel)
here::here()
```

```{r}
load("data/study5_dfm.RData")
data_scatter <- study5$partisan_cos_scores
mid <- mean(data_scatter$partisanlean)
```

```{r}
LIBandCONSERV <- ggplot(data_scatter, aes(x = libcos, 
                                          y = concos, 
                                          label = rownames(feature1))) + 
  geom_abline(intercept = 0, slope = 1) + 
  geom_label_repel(size =6, aes(color = partisanlean, 
                                label = feature1, 
                                hjust = 0,
                                vjust = 0), 
                   data = data_scatter, 
                   max.overlaps = getOption("ggrepel.max.overlaps", 
                                            default = 100), 
                   segment.size = 0, 
                   label.padding = .3, 
                   box.padding = .3, 
                   point.padding = .5, 
                   force = 2)

  LIBandCONSERV+scale_color_gradient2(midpoint = mid, 
                        low = "navyblue", 
                        mid = "grey50", 
                        high = "darkred", 
                        space = "Lab" ) +
  theme(legend.position = "none", 
        panel.background = element_rect(fill = "white",
                                        colour = "white", 
                                        linewidth = 0.5, 
                                        linetype = "solid"),
        panel.grid.major = element_line(linewidth = 0.5, 
                                        linetype = 'solid',
                                        colour = "gray90"), 
        panel.grid.minor = element_line(linewidth = 0.25, 
                                        linetype = 'solid', 
                                        colour = "gray90"),
        axis.title.x = element_text(size = 20), 
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14)) + 
  scale_x_continuous(limits = c(-.06, .2), n.breaks = 6) + 
  scale_y_continuous(limits = c(-.06, .28), n.breaks = 6) +
  xlab("Liberal Cosine Value") + ylab("Conservative Cosine Value")
```











