
> Adaptation from Essig and DellaPosta (2024)

# Term Network

```{r}
library(quanteda)
library(tidyverse)
library(quanteda.textstats)
library(igraph)
library(ggplot2)
library(ggrepel)
library(pheatmap)
library(RColorBrewer)
library(viridis)
library(stringr)
library(purrr)
```

```{r}
lib_words <- rio::import('data/partisan_terms.csv') %>% 
    filter(p == 2) %>% 
    select(terms) %>% 
    as_vector() %>% 
    paste(., collapse = "|")

conserv_words <- rio::import('data/partisan_terms.csv') %>% 
    filter(p == 1) %>% 
    select(terms) %>% 
    as_vector() %>% 
    paste(., collapse = "|")

replace_words <- function(string, words, replacement) {
  for (word in words) {
    string <- str_replace_all(string, word, replacement)
  }
  return(string)
}

csv_to_tfidf <- function(path_to_csv){
  # Read in csv
  df = read.csv(here::here(path_to_csv)) %>% 
    mutate(
      posttoken_bio = gsub("[[:punct:]]", "", posttoken_bio))
  
  # Partisan Aggregated Nodes
  postoken_bio_partisan <- lapply(df$posttoken_bio, 
                                replace_words, 
                                lib_words, 
                                replacement = "liber")
  
  df$posttoken_bio_partisan <- lapply(postoken_bio_partisan, 
                                          replace_words, 
                                          conserv_words, 
                                          replacement = "conserv") %>% 
                                       unlist()
  
  
  # Term Frequencey-Inverse Document Frequency
  data_tfidf <- corpus(df, text_field = "posttoken_bio") %>% 
                tokens() %>% 
                dfm(., 
                   verbose = FALSE, 
                   remove_padding = TRUE) %>% 
               dfm_trim(., 
                   min_docfreq = 0.001, 
                   docfreq_type = "prop") %>% 
               dfm_subset(., 
                          ntoken(.) > 0) %>% 
               dfm_tfidf()
  
  # Cosine similarity matrix
  terms_cosine <- textstat_simil(data_tfidf, 
                                 margin = "features", 
                                 method = "cosine") %>% 
                  as.matrix()
  
  #Graph of Terms and Connections
  terms_graph <- graph_from_adjacency_matrix(terms_cosine,
                                         mode = "undirected", 
                                         weighted = TRUE, 
                                         diag = FALSE)

  # Prepare for scatterplot
  scatter_TFIDF <- corpus(df, text_field = "posttoken_bio_partisan") %>% 
                tokens() %>% 
                dfm(., 
                   verbose = FALSE, 
                   remove_padding = TRUE) %>% 
               dfm_trim(., 
                   min_docfreq = 0.001, 
                   docfreq_type = "prop") %>% 
               dfm_subset(., 
                          ntoken(.) > 0) %>% 
               dfm_tfidf()
          
  #compute partisan cosines
  scatter_COSliber <- as.data.frame(textstat_simil(scatter_TFIDF, 
                                                   scatter_TFIDF[, c("liber")], 
                                                   method = "cosine", 
                                                   margin = "features")) 
  
  scatter_COSconserv <- as.data.frame(textstat_simil(scatter_TFIDF, 
                                                     scatter_TFIDF[,   c("conserv")], 
                                                     method = "cosine", 
                                                     margin = "features")) 
  
  #Liberal cosines
  COSlib <- subset(scatter_COSliber, select = c("feature1", "cosine"))
  COSlib$libcos <- COSlib$cosine
  COSlib <- subset(COSlib, select = c("feature1", "libcos"))  
  COSlib <- COSlib[order(COSlib$libcos, decreasing = TRUE),]  
  COSlib <- COSlib[0:110,]  
  COSlib <- subset(COSlib, feature1!="conserv")  
  
  #Conservative cosines
  COScon <- subset(scatter_COSconserv, select = c("feature1", "cosine"))
  COScon$concos <- COScon$cosine
  COScon <- subset(COScon, select = c("feature1", "concos"))
  COScon <- COScon[order(COScon$concos, decreasing = TRUE),]
  COScon <- COScon[0:110,]
  COScon <- subset(COScon,feature1!='liber' )
  
  
  COSall <- full_join(COSlib, COScon)
  COSall["libcos"][is.na(COSall["libcos"])] <- 0
  COSall["concos"][is.na(COSall["concos"])] <- 0
  COSall$partisanlean <- (COSall$concos - COSall$libcos)
  COSall_collapsed <- COSall %>%
    mutate(party = case_when(partisanlean < 0 ~ 'Liberal',
                             partisanlean > 0 ~ 'Conservative'))
  COSall_collapsed <- COSall_collapsed[!grepl("behind",   COSall_collapsed$feature1),]
  COSall_collapsed <- COSall_collapsed[!grepl("er", COSall_collapsed$feature1),]
  
  data_scatter <- COSall_collapsed
  
  mid <- mean(data_scatter$partisanlean)
  
  LIBandCONSERV <- ggplot(data_scatter, aes(x = libcos, 
                                            y = concos, 
                                            label = rownames(feature1))) + 
    geom_abline(intercept = 0, slope = 1) + 
    geom_label_repel(size =6, aes(color = partisanlean, 
                                  label = feature1, 
                                  hjust = 0,
                                  vjust = 0), 
                     data = data_scatter, 
                     max.overlaps = getOption("ggrepel.max.overlaps", 
                                              default = 100), 
                     segment.size = 0, 
                     label.padding = .3, 
                     box.padding = .3, 
                     point.padding = .5, 
                     force = 2) + 
    scale_color_gradient2(midpoint = mid, 
                          low = "navyblue", 
                          mid = "grey50", 
                          high = "darkred", 
                          space = "Lab" ) + 
    theme(legend.position = "none", 
          panel.background = element_rect(fill = "white",
                                          colour = "white", 
                                          linewidth = 0.5, 
                                          linetype = "solid"),
          panel.grid.major = element_line(linewidth = 0.5, 
                                          linetype = 'solid',
                                          colour = "gray90"), 
          panel.grid.minor = element_line(linewidth = 0.25, 
                                          linetype = 'solid', 
                                          colour = "gray90"),
          axis.title.x = element_text(size = 20), 
          axis.title.y = element_text(size = 20),
          plot.title = element_text(size = 25),
          axis.text.x = element_text(size=14),
          axis.text.y = element_text(size=14)) + 
    scale_x_continuous(limits = c(-.06, .2), n.breaks = 6) + 
    scale_y_continuous(limits = c(-.06, .28), n.breaks = 6) +
    xlab("Liberal Cosine Value") + ylab("Conservative Cosine Value")
  output = list(
    df = df,
    data_tfidf = data_tfidf,
    tfidf_mat = as.matrix(data_tfidf), 
    cos_sim_mat = terms_cosine,
    cos_sim_fig = terms_graph,
    partisan_tfidf = scatter_TFIDF, 
    partisan_cos_scores = data_scatter,
    partisan_figure = LIBandCONSERV
  )
}
```

```{r}
study1 <- csv_to_tfidf("data/study1.csv")
study2 <- csv_to_tfidf("data/study2.csv")
study3 <- csv_to_tfidf("data/study3.csv")
study4 <- csv_to_tfidf("data/study4.csv")
study5 <- csv_to_tfidf("data/study5.csv")
```

